### ISSUE TITLE
Apply for scribbles of the ACDC dataset.

### ISSUE THREAD

**Issue by Luoxd1996** [gvalvano/multiscale-adversarial-attention-gates#1]
Hi Dr. Valvano
     Excellent work. Could you share the scribbles of the ACDC dataset? I would be very grateful if you could reply.
Best wish,
Xiangde Luo.

**Comment by gvalvano** [comment]
Hi Xiangde Luo,
the dataset will be available shortly (~1 or 2 weeks max), the time to prepare its documentation and upload it to the server :) I'll keep you posted

**Comment by gvalvano** [comment]
Hi @Luoxd1996 :) data is now available at this link: https://gvalvano.github.io/wss-multiscale-adversarial-attention-gates/data
